### ISSUE TITLE
AWS Calico DaemonSet trying to schedule pods on Fargate nodes

### ISSUE THREAD

**Issue by itssimon** [aws/eks-charts#124]
I'm using the AWS Calico Helm chart on an EKS cluster that uses normal EC2 nodes and Fargate. I know that Calico is not supported on Fargate, but I would still like it to run on the EC2 nodes.

The Calico DaemonSet, however, is configured in such a way that it attempts to schedule Calico pods on the Fargate "nodes", which fails:

          tolerations:
            # Make sure calico/node gets scheduled on all nodes.
            - effect: NoSchedule
              operator: Exists

`0/7 nodes are available: 1 Insufficient pods, 6 node(s) didn't match node selector.`

I believe this could be solved using node affinity.

**Comment by haouc** [comment]
@itssimon 
If you still have concerns, please be aware of our latest announcement. Since we are deprecating Calico charts in this repo, we recommend you to check our [important announcement](https://github.com/aws/eks-charts/tree/master/stable/aws-calico) and suggested [installation instruction](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) for required or latest Calico version. You can also refer to [Calico configuration reference](https://projectcalico.docs.tigera.io/reference/installation/api).
If you need migrate Calico from non-operator based installation to operator based installation, we recommend you to check [this Tigera document](https://projectcalico.docs.tigera.io/maintenance/operator-migration). 
If you need upgrade you calico operator but you didn't install Calico via helm, you can check [this Tigera document](https://projectcalico.docs.tigera.io/getting-started/kubernetes/quickstart). Please being aware that any customized installation may encounter compatibility issue during upgrading.
If you have any issues or questions during Calico resources installation/upgrading/deletion, please refer to the [README](https://github.com/aws/eks-charts/tree/master/stable/aws-calico) and send request to Calico repositories.
I am closing this ticket due to unsupported charts upgrade. Please feel free to send questions to our triage email ([k8s-awscni-triage@amazon.com](mailto:k8s-awscni-triage@amazon.com)).
