### ISSUE TITLE
Upgrade eniconfigs.crd.k8s.amazonaws.com to apiextensions.k8s.io/v1 by k8s 1.22

### ISSUE THREAD

**Issue by TBBle** [aws/eks-charts#195]
Per https://github.com/kubernetes/kubernetes/issues/82022, the currently-used API version [`apiextensions.k8s.io/v1beta1`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#customresourcedefinition-v1beta1-apiextensions-k8s-io) will stop being served by default in k8s 1.22.

This is worth looking at sooner rather than later, as it's not a trivial change. [`apiextensions.k8s.io/v1`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#customresourcedefinition-v1-apiextensions-k8s-io) makes a [structural schema mandatory](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#specifying-a-structural-schema), and the current CRD definition doesn't provide a schema at all.

**Comment by jaypipes** [comment]
Hi @TBBle! Good catch on this. I think, however, that this issue should be logged against the aws-vpc-cni-k8s repository, since the ENIConfig CRD originates there:

https://github.com/aws/amazon-vpc-cni-k8s/blob/d938e5e7590915a5126b2ee71fcc71b4ad7666f6/pkg/apis/crd/v1alpha1/types.go#L17

https://github.com/aws/amazon-vpc-cni-k8s/blob/d938e5e7590915a5126b2ee71fcc71b4ad7666f6/config/v1.6/aws-k8s-cni.yaml#L161

Feel like submitting this issue over there and we'll close this one out with a reference link?

**Comment by TBBle** [comment]
Huh, yeah. I was looking at that Github project, I must have mentally jumped tracks and then lodged the report here instead. >_<

Opened in the correct place as https://github.com/aws/amazon-vpc-cni-k8s/issues/1074
