### ISSUE TITLE
aws-node-termination-handler upgrade failed from v1.5.0 to v1.7.0

### ISSUE THREAD

**Issue by prikesh-patel** [aws/eks-charts#251]
Attempting to upgrade existing installation of aws-node-termination-handler from v1.5.0 (chart v0.8.0) to v1.7.0 (chart v0.9.5) which gives the following error
```
Upgrade "aws-node-termination-handler" failed: cannot patch "aws-node-termination-handler" with kind DaemonSet: DaemonSet.apps "aws-node-termination-handler" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"aws-node-termination-handler", "app.kubernetes.io/name":"aws-node-termination-handler", "kubernetes.io/os":"linux"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```
This is related to issue #215 

I've tried specifying the fields `nodeSelectorTermsOs` and `nodeSelectorTermsArch` under the values as follows
```
nodeSelectorTermsOs: "kubernetes.io/os"
nodeSelectorTermsArch: "kubernetes.io/arch"
```
but still get the same error as above.

The same error also occurs when trying to upgrade aws-node-termination-handler from v1.5.0 to v1.6.0.

An uninstall and reinstall of chart does work but a clean upgrade would be ideal due to the large number of clusters running aws-node-termination-handler v1.5.0.

**Comment by bwagner5** [comment]
Hi @prikesh-patel , I believe if you set the values as follows, it will upgrade cleanly:

```
nodeSelectorTermsOs: "beta.kubernetes.io/os"
nodeSelectorTermsArch: "beta.kubernetes.io/arch"
```

K8s will stop supporting the beta key in 1.19 I believe, so you will need to switch to the non-beta keys before upgrading to k8s 1.19.

**Comment by prikesh-patel** [comment]
Hi @bwagner5 , I set the fields to what you said and have got pretty much the same error when upgrading
```
Upgrade "aws-node-termination-handler" failed: cannot patch "aws-node-termination-handler" with kind DaemonSet: DaemonSet.apps "aws-node-termination-handler" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/instance":"aws-node-termination-handler", "app.kubernetes.io/name":"aws-node-termination-handler", "beta.kubernetes.io/os":"linux"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable
```

Only this time it says `"beta.kubernetes.io/os":"linux"` instead of `"kubernetes.io/os":"linux"` under `MatchLabels`.

I'm also testing this on k8s version 1.15, 1.16 and 1.17

**Comment by marpada** [comment]
Can the upgrade process be documented in the README?

**Comment by nchowning** [comment]
Any updates on the upgrade process for this? I'm upgrading from `1.14` to `1.16` on k8s `v1.21.5`. Looking at our current `1.14` installation of aws-node-termination-handler, it seems like we're already using the non-beta keys:

```
nodeSelector:                                                                                                                                                                                
  kubernetes.io/os: linux
```

**Comment by fitchtech** [comment]
@nchowning @marpada I've found what the issue is and unfortunately with the current chart version it will fail to upgrade due to a change in match labels _helper.tpl 

The original version I have deployed,  0.16.0 has this:
```yaml
matchLabels:
      app.kubernetes.io/name: aws-node-termination-handler
      app.kubernetes.io/instance: aws-node-termination-handler
      kubernetes.io/os: linux
```
When upgrading to 0.18.1 has this:
```yaml
    matchLabels:
      app.kubernetes.io/name: aws-node-termination-handler
      app.kubernetes.io/instance: aws-node-termination-handler
      app.kubernetes.io/component: deployment
```

The reason is a change this made to _helpers.tpl hardcoded a new value `app.kubernetes.io/component: deployment`

You can compare these two tagged releases. The first for 0.16.0 includes `defaultNodeSelectorTermsOs` however that's removed in the latest version. The second link for 0.18.1 shows the hardcoded value that's been added. Which cause `selector.matchLabels` is immutable, the selector values cannot change when doing an upgrade. 

https://github.com/aws/eks-charts/blob/v0.0.70/stable/aws-node-termination-handler/templates/_helpers.tpl#L98
https://github.com/aws/eks-charts/blob/v0.0.85/stable/aws-node-termination-handler/templates/_helpers.tpl#L73

This unfortunately means you can not do a Helm upgrade given that new hardcoded value. However, given that the Node Termination Handler is going to poll either IMDS or SQS it's safe to uninstall it and do a fresh install. That worked for me. Not ideal but it seems to be the only option for now.

**Comment by jstefankowski** [comment]
@fitchtech Good info, thanks !  
Is there a workaround for 0.19.3 by any chance ?  I'm getting similar error when upgrading from 0.15.1 to 0.19.3.

null_resource.aws_node_termination_handler (local-exec): Error: UPGRADE FAILED: cannot patch "aws-node-termination-handler" with kind DaemonSet: DaemonSet.apps "aws-node-termination-handler" is invalid: spec.selector: Invalid value: v1.LabelSelector{MatchLabels:map[string]string{"app.kubernetes.io/component":"daemonset", "app.kubernetes.io/instance":"aws-node-termination-handler", "app.kubernetes.io/name":"aws-node-termination-handler", "kubernetes.io/os":"linux"}, MatchExpressions:[]v1.LabelSelectorRequirement(nil)}: field is immutable

**Comment by prikesh-patel** [comment]
Closing as the `matchLabels` field is immutable, and changing this requires a manual deletion of the relevant daemonset
