### ISSUE TITLE
kubectl can't get virtualservice resources by "virtualservice" type

### ISSUE THREAD

**Issue by FanDoubleLucky** [aws/eks-charts#259]
Hi,
I deploy an appmesh by appmesh k8s crd. Then when I use "kubectl get virtualservice" to search virtualservice resources, the result is "No resources found". But when I use "kubectl get virtualservice.appmesh.k8s.aws" to search virtualservice resources, it returns virtualservice resources correctly.
For other crd resources (virtualnode, virtualrouter), whether I use abbreviations or full names of crd to search, I can get the results correctly.
Why virtualservice is special?
Thanks!

**Comment by achevuru** [comment]
@FanDoubleLucky Nothing special about Virtualservice and it should work similar to other resources. Also, since you are seeing "No Resources found" as opposed to "the server doesn't have a resource type "virtualservice"" for example tells us that apiserver itself identifies the resource type. Do you have any old crds in your system for these resources? What do you have in your virtualservice resource yaml files?

**Comment by FanDoubleLucky** [comment]
@achevuru I checked the crd list and I found there is istio virtualservice crd. I think this may be due to the confusion between istio virtualservice and appmesh virtualservice. In k8s, the abbreviations of their type names are the same. So when I run "kubectl get virtualservice", k8s thinks it is to search the istio virtualservices.
Thanks!
