### ISSUE TITLE
Unable to install calico crds

### ISSUE THREAD

**Issue by jseiser** [aws/eks-charts#315]
```
kubectl apply -k github.com/aws/eks-charts/tree/master/stable/aws-calico/crds

error: evalsymlink failure on '/private/var/folders/_v/82h1zgqd5zg63wr6wb7t5qdw0000gp/T/kustomize-324908507/tree/master/stable/aws-calico/crds' : lstat /private/var/folders/_v/82h1zgqd5zg63wr6wb7t5qdw0000gp/T/kustomize-324908507/tree: no such file or directory
```

This is just a EKS 1.18 cluster.

**Comment by amoniaka-knabino** [comment]
Try this:
`kubectl apply -k "github.com/aws/eks-charts/stable/aws-load-balancer-controller//crds?ref=master"`

**Comment by amoniaka-knabino** [comment]
try this: `kubectl apply -k "github.com/aws/eks-charts/stable/aws-calico//crds?ref=master"`

**Comment by GataullinRR** [comment]
Also experience this issue
My console output:
```
radmir@radmir-qtu100:/tmp$ kubectl apply -k github.com/aws/eks-charts/tree/master/stable/aws-calico/crds
error: evalsymlink failure on '/tmp/kustomize-435678547/tree/master/stable/aws-calico/crds' : lstat /tmp/kustomize-435678547/tree: no such file or directory
```
```
radmir@radmir-qtu100:/tmp$ kubectl apply -k "github.com/aws/eks-charts/tree/master/stable/aws-calico/crds"
error: evalsymlink failure on '/tmp/kustomize-244643629/tree/master/stable/aws-calico/crds' : lstat /tmp/kustomize-244643629/tree: no such file or directory
```
Fix it please

**Comment by haouc** [comment]
@jseiser 
Since we are deprecating Calico charts in this repo, we recommend you to check our [important announcement](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico) and suggested [installation instruction](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) for required or latest Calico version. You can also refer to [Calico configuration reference](https://projectcalico.docs.tigera.io/reference/installation/api).
I am closing this ticket due to unsupported charts upgrade. Please feel free to send questions to our triage email (k8s-awscni-triage@amazon.com).
