### ISSUE TITLE
AWS LB Controller cannot be automated because CRD step

### ISSUE THREAD

**Issue by yardensachs** [aws/eks-charts#374]
Most helm chart's installation can be automated with terraform, however, the need to have a step to install the CRD is blocking that. Helm has this way of dealing with CRD: https://helm.sh/docs/chart_best_practices/custom_resource_definitions/

**Comment by stefanprodan** [comment]
All AWS charts in this repo are compatible with Helm v3, the CRDs are placed in the `chart/crds` dir so `helm install` will work without any extra steps. The reason we tell users to apply the CRDs with kubectl is due to Helm not being able to upgrade CRDs, it will install them, but it will not apply them on helm upgrade.
