### ISSUE TITLE
[aws-calico] CRD install instructions fail with kubectl error 

### ISSUE THREAD

**Issue by spingel** [aws/eks-charts#377]
h3. Steps

When I follow the instructions for installing the aws-calico CRDs I get the following kubectl error:

```sh
# kubectl apply -k github.com/aws/eks-charts/tree/master/stable/aws-calico/crds
error: evalsymlink failure on '/private/var/folders/_f/8fn88h2x6yq66kccq6g180600000gn/T/kustomize-777576986/tree/master/stable/aws-calico/crds' : lstat /private/var/folders/_f/8fn88h2x6yq66kccq6g180600000gn/T/kustomize-777576986/tree: no such file or directory
```

This is on Mac OS 10.15 with kubectl 1.19.4:

```
# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T01:09:16Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"darwin/amd64"}
```

h3. Work-around

The following command works: `kubectl apply -k github.com/aws/eks-charts/stable/aws-calico/crds`

**Comment by spingel** [comment]
The documentation also needs to be updated on https://hub.kubeapps.com/charts/aws/aws-calico .

**Comment by fawadkhaliq** [comment]
@jayanthvn feel free to re-assign to Alex/Hao to help here

**Comment by 8enmann** [comment]
I saw this same error today.

**Comment by haouc** [comment]
@8enmann @spingel 
Since we are deprecating Calico charts in this repo, we recommend you to check our [important announcement](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico) and suggested [installation instruction](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) for required or latest Calico version. You can also refer to [Calico configuration reference](https://projectcalico.docs.tigera.io/reference/installation/api).
I am closing this ticket due to unsupported charts upgrade. Please feel free to send questions to our triage email (k8s-awscni-triage@amazon.com).
