### ISSUE TITLE
AWS Load Balancer Controller Yaml should have a namespace metadata field

### ISSUE THREAD

**Issue by ritalint** [aws/eks-charts#408]
At the moment it not possible to pass the correct namespace for AWS load balancer controller deployment with `--namespace `-option, using `helm template` -command. When comparing to e.g. app mesh controller template, it has this metadata field `namespace: {{ .Release.Namespace }}` https://github.com/aws/eks-charts/blob/master/stable/appmesh-controller/templates/deployment.yaml#L5 whereas AWS Load Balancer Controller deployment does not have this: https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/templates/deployment.yaml

This would be important to fix, since now when deploying the LB controller with helm template, resources get deployed to `"default"` namespace instead of the needed `"kube-system"`.

**Comment by kishorj** [comment]
@ritalint, the release namespace is omitted to provide some flexibility for post-render operations. For example, something like
```
helm template | kubectl apply -n foo -f -
```
Are there any workflows or tools that don't support specifying the namespace?

**Comment by parviste** [comment]
We currently have decoupled the templating and kubectl apply steps. When we apply the generated yaml, we no longer know (nor should we need to care) where it came from.

We end up piping all the generated yaml into kubectl in one step. Thus, the proposed solution does not work.

Another solution is to take the output of `helm template`, and modify it so that it includes the namespace information. This is of course possible, but adds extra work.

However, I think one point to consider here is the inconsistency: One chart on this repository supports adding namespace information, another does not, which leads to surprising results. Some degree of consistency seems like a value in itself, regardless if the issue can be worked around.

**Comment by kishorj** [comment]
@parviste feel free to raise the PR.
