### ISSUE TITLE
[AWS Load Balancer Controller ] helm chart does not expose alb-name-prefix parameters

### ISSUE THREAD

**Issue by alexmnyc** [aws/eks-charts#512]
Based on https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/e5c5d6e293e2b81167791ca9b2cea39fc5af7078/internal/ingress/controller/config/config.go#L75 it should be possible to customize the prefix of the ALB. It is needed for enterprises that have predefined IAM policies around resource names. Please externalize the helm chart to provide ability to set it

**Comment by kishorj** [comment]
@alexmnyc, the `alb-name-prefix` flag is not supported on v2 version of the controller. There is an open feature request for this - https://github.com/kubernetes-sigs/aws-load-balancer-controller/issues/1788.

The v2 release uses fixed name pattern for the ALB/NLB - `k8s-<namespacedName>-<hash>`. The upcoming v2 version will also support specifying custom LB name via annotation.

Since the controller for this helm chart doesn't support this flag, there is no point exposing the configuration from the chart. I'm closing the issue for now, feel free to put your comments in the controller issue 1788.
