### ISSUE TITLE
[aws-calico] Liveness/Readiness probe failing

### ISSUE THREAD

**Issue by prikesh-patel** [aws/eks-charts#552]
**Describe the bug**
There are consistent warnings on the pod describing the liveness and readiness probe failing. There are also no errors showing in the logs.

**Steps to reproduce**
Deploy v0.3.6 of the _aws-calico_ chart on an EKS v1.20 cluster.

**Expected outcome**
No liveness/readiness probe failing warnings on _aws-calico_ pods.

**Environment**

* Chart name: aws-calico
* Chart version: 0.3.6
* Kubernetes version: v1.20
* Using EKS (yes/no), if so version? Yes, v1.20

**Additional Context**:
The only configuration applied on top for the chart values are some resource limits.

**Comment by stevehipwell** [comment]
The version of Calico in chart `v0.3.6` (Calico `v3.19.1`) has a [long standing issue](https://github.com/projectcalico/calico/issues/4518) on non-Calico CNIs and should never have been merged into here. For what it's worth patches to the `v3.15` release line should have been.

**Comment by shapirov103** [comment]
Can someone share ETA for this fix? eks-charts fail consistently on readiness probe still. The github repo is not the best option to lock down the version and implement controlled upgrades.

**Comment by haouc** [comment]
@shapirov103 please consider using the linked charts by @jayanthvn. We are making changes on supporting Calico charts and can't make updates on Calico charts in eks-charts at this moment. We will publish updates very soon in our GitHub repositories (amazon-vpc-cni-k8s and eks-charts). Thanks.

**Comment by shapirov103** [comment]
Thanks. 
If anyone is interested the current workaround is to apply higher mem limits for the helm chart, since the issue was OOM:

"calico.node.requests.memory", "64Mi"
"calico.node.limits.memory", "100Mi"

**Comment by haouc** [comment]
@shapirov103 @prikesh-patel 
We are aware that this issue has been fixed in Calico. Since we are deprecating Calico charts in this repo, we recommend you to check our [important announcement](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico) and suggested [installation instruction](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) for required or latest Calico version. You can also refer to [Calico configuration reference](https://projectcalico.docs.tigera.io/reference/installation/api).
I am closing this ticket due to unsupported charts upgrade. Please feel free to send questions to our triage email (k8s-awscni-triage@amazon.com).
