### ISSUE TITLE
[aws-node-termination-handler] No PDB

### ISSUE THREAD

**Issue by stevehipwell** [aws/eks-charts#553]
**Is your feature request related to a problem?**
As there is no PDB for the aws-node-termination-handler chart it isn't possible to run multiple replicas in different node groups that aren't both terminated at the same time.

**Is your feature request related to a specific Helm chart, if yes mention name of the chart?**
aws-node-termination-handler

**Describe the solution you'd like**
Add a PDB to the chart, I'm happy to open a PR to do this but I'm not sure if the chart in this repo is only a copy of the one at [aws/aws-node-termination-handler](https://github.com/aws/aws-node-termination-handler/tree/main/config/helm/aws-node-termination-handler)? If it is how are the two kept in sync? I can open the PR there.

**Describe alternatives you've considered**
I've manually configured a PDB but it should be in the chart as it is for aws-load-balancer-controller.

**Comment by bwagner5** [comment]
Hey Steve! I think a PDB would be great for the NTH deployment and we'd love you help!  

You are correct that we accept PRs to NTH's Helm Chart in the app repo [here](https://github.com/aws/aws-node-termination-handler) rather than eks-charts. When we release NTH versions, we have an automated process that will sync it over to eks-charts :)

**Comment by stevehipwell** [comment]
@bwagner5 I've opened PR https://github.com/aws/aws-node-termination-handler/pull/463 for this.
