### ISSUE TITLE
[aws-calico] Chart version v0.3.6 introduces a known defect

### ISSUE THREAD

**Issue by stevehipwell** [aws/eks-charts#565]
**Describe the bug**
The _aws-calico_ chart `v0.3.6` release introduces a [known Calico defect](https://github.com/projectcalico/calico/issues/4518) with non-Calico CNIs breaking everyone who installs it.

**Steps to reproduce**
Follow the steps in the linked issue.

**Expected outcome**
A working Calico installation with the aws-vpc-cni (the only officially supported CNI).

**Environment**

* Chart name: aws-calico
* Chart version: 0.3.6
* Kubernetes version: 1.18, 1.19, 1.20, 1.21
* Using EKS (yes/no), if so version? EKS 1.18, 1.19, 1.20, 1.21

**Additional Context**:
The new [Installing Calico guide](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) will also result in a broken Calico installation.

**Comment by aquam8** [comment]
The new Calico release v3.19.2 fixes this issue - it's a simple `appVersion: 3.19.2` update for the aws-calico chart.

**Comment by jayanthvn** [comment]
Upgrade is done here https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico, we are working on syncing the changes to eks-charts. Sorry for the delay.

/cc @haouc

**Comment by haouc** [comment]
@stevehipwell 
Since we are deprecating Calico charts in this repo, we recommend you to check our [important announcement](https://github.com/aws/amazon-vpc-cni-k8s/tree/master/charts/aws-calico) and suggested [installation instruction](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) for required or latest Calico version. You can also refer to [Calico configuration reference](https://projectcalico.docs.tigera.io/reference/installation/api). The issue was fixed in Calico already.
I am closing this ticket due to unsupported charts upgrade. Please feel free to send questions to our triage email (k8s-awscni-triage@amazon.com).

**Comment by stevehipwell** [comment]
@haouc I'd already solved this before I reported it, this issue was to help anyone who had the issue and to try and get it resolved.

FYI I created an idiomatic Tigera Operator [Helm chart](https://artifacthub.io/packages/helm/stevehipwell/tigera-operator) to install and manage Calico on all our EKS clusters as the official one wasn't/isn't production ready.
