### ISSUE TITLE
Helm chart preference for Calico: aws-calico helm chart vs  Project Calico 

### ISSUE THREAD

**Issue by patrickmarshallcb** [aws/eks-charts#596]
We are piloting Calico as a network policy engine. We've experimented with charts from:
- https://docs.projectcalico.org/charts
- https://github.com/aws/eks-charts/tree/master/stable/aws-calico

I'm looking to get an understanding as to why are you maintaining a helm chart related to Calico as opposed to utilizing the  Project Calico provided chart at [](https://docs.projectcalico.org/charts). They both provide the same functionality so just want to get some feedback on preference and choice. 

Environment:

- Kubernetes version (use kubectl version): 1.19 (EKS)
- CNI Version: v1.8.0-eksbuild.1
- EKS managed nodes AMI version 1.19.13-20210813

**Comment by PeterSzegedi** [comment]
It would be useful to have official guidance about this for our use case too

**Comment by kammar87** [comment]
We would like to understand it as well before proceeding with the project,

**Comment by mprimeaux** [comment]
We are considering to use this project globally for our platform portfolio and would sincerely appreciate the support on this question. Your help is greatly appreciated.

**Comment by nuriel77** [comment]
>But the sync to eks-charts is missing which we will take up as priority and update this asap.

Hello! Any updates on the progress/expected time?

**Comment by kammar87** [comment]
Hello,
Do you have any updates on this issue? It's starting to be a blocker for us.

**Comment by haouc** [comment]
Hello everyone, if you still have concerns on AWS EKS managed Calico charts, please be aware of our latest announcement. Since we are deprecating Calico charts in this repo, we recommend you to check our [important announcement](https://github.com/aws/eks-charts/tree/master/stable/aws-calico) and suggested [installation instruction](https://docs.aws.amazon.com/eks/latest/userguide/calico.html) for required or latest Calico version. You can also refer to [Calico configuration reference](https://projectcalico.docs.tigera.io/reference/installation/api).
If you need migrate Calico from non-operator based installation to operator based installation, we recommend you to check [this Tigera document](https://projectcalico.docs.tigera.io/maintenance/operator-migration). 
If you need upgrade you calico operator but you didn't install Calico via helm, you can check [this Tigera document](https://projectcalico.docs.tigera.io/getting-started/kubernetes/quickstart). Please being aware that any customized installation may encounter compatibility issue during upgrading.
If you have any issues or questions during Calico resources installation/upgrading/deletion, please refer to the [README](https://github.com/aws/eks-charts/tree/master/stable/aws-calico) and send request to Calico repositories.
I am closing this ticket due to unsupported charts upgrade. Please feel free to send questions to our triage email ([k8s-awscni-triage@amazon.com](mailto:k8s-awscni-triage@amazon.com)).
