### ISSUE TITLE
Can aws-load-balancer-controller be deployed as a sibling sub-chart?

### ISSUE THREAD

**Issue by murphymagic** [aws/eks-charts#765]
It appears that aws-load-balancer-controller needs to be deployed before I deploy an ingress, in order to work.
When I deploy it as a sub-chart simultaneously with other sub-charts that contain ingresses, the ingresses to not get created.
Is this the way aws-load-balancer-controller works?

**Comment by kishorj** [comment]
@murphymagic, does your ingress resource get created, and no ALB provisioned, or ingress creation itself fail due to lb controller webhook. If ingress got created successfully, the lb controller will eventually reconcile the ingress once it is ready and provision ALB resources.

If you have further concerns, please open an issue in the upstream repo - https://github.com/kubernetes-sigs/aws-load-balancer-controller/
